#drafted by Jeremy VanDerWal ( jjvanderwal@gmail.com ... www.jjvanderwal.com )
#GNU General Public License .. feel free to use / distribute ... no warranties

################################################################################
################################################################################
### define functions

##function to write things out in binary for linux
twrite = function(x,y) {
	f = file(y,'wb')
		write.table(x,row.names=FALSE,sep=",",quote=FALSE,file=f)
	close(f)
}
twrite2 = function(x,y) {
	f = file(y,'wb')
		write.table(x,row.names=FALSE,sep=",",quote=FALSE,file=f,col.names=FALSE)
	close(f)
}

#function to write input data files
write.inputs = function(idx) {

	###make the pu.dat
	pu = aggregate(tdata[,'area'],by=list(id=tdata[,'PU']),sum) #aggregate to pu
	colnames(pu)=c('id','cost') #add appropriate colnames
	twrite(pu,file.path(idx,"pu.dat"))

	###make the puorder.dat
	puorder = aggregate(tdata[,'area'],by=list(species=tdata[,'FU'],pu=tdata[,'PU']),sum) #aggregate to pu & fu
	colnames(puorder)=c('species','pu','amount'); puorder = puorder[,c('species','pu','amount')] #add appropriate colnames & reorder
	twrite(puorder,file.path(idx,'/puorder.dat'))

	###make the sporder.dat
	sporder = puorder
	sporder = sporder[order(sporder[,'species'],sporder[,'pu']),] #reorder for species first
	twrite(sporder,file.path(idx,'/sporder.dat'))
}

#function to create input directory
create.input.dat = function(od,id,tt) {
	tstr = 'Input file for Annealing program.'
	tstr = c(tstr,'')
	tstr = c(tstr,'This file generated by Inedit.exe.')
	tstr = c(tstr,'written by Ian Ball and Hugh Possingham.')
	tstr = c(tstr,'iball@maths.adelaide.edu.au')
	tstr = c(tstr,'hpossing@maths.adelaide.edu.au')
	tstr = c(tstr,'')
	tstr = c(tstr,'General Parameters')
	# tstr = c(tstr,'VERSION 0.1')
	tstr = c(tstr,'BLM  1')
	tstr = c(tstr,'PROP  0.5')
	tstr = c(tstr,'RANDSEED -1')
	tstr = c(tstr,'NUMREPS 100')
	tstr = c(tstr,'')
	tstr = c(tstr,'Annealing Parameters')
	tstr = c(tstr,'NUMITNS 10000000')
	tstr = c(tstr,'STARTTEMP -1')
	tstr = c(tstr,'NUMTEMP 10000')
	tstr = c(tstr,'')
	tstr = c(tstr,'Cost Threshold')
	tstr = c(tstr,'COSTTHRESH  0.00000000000000E+0000')
	tstr = c(tstr,'THRESHPEN1  1.40000000000000E+0001')
	tstr = c(tstr,'THRESHPEN2  1.00000000000000E+0000')
	tstr = c(tstr,'')
	tstr = c(tstr,'Input Files')
	tstr = c(tstr,paste('INPUTDIR ',id,sep=''))
	tstr = c(tstr,'PUNAME pu.dat')
	tstr = c(tstr,'SPECNAME spec.dat')
	tstr = c(tstr,'PUVSPRNAME puorder.dat')
	# tstr = c(tstr,'MATRIXSPORDERNAME sporder.dat')
	tstr = c(tstr,'')
	tstr = c(tstr,'Save Files')
	tstr = c(tstr,paste('SCENNAME rep',sprintf('%02i',tt),sep=''))
	tstr = c(tstr,'SAVERUN 3')
	tstr = c(tstr,'SAVEBEST 3')
	tstr = c(tstr,'SAVESUMMARY 3')
	tstr = c(tstr,'SAVESCEN 3')
	tstr = c(tstr,'SAVETARGMET 3')
	tstr = c(tstr,'SAVESUMSOLN 3')
	tstr = c(tstr,'SAVEPENALTY 3')
	tstr = c(tstr,'SAVELOG 2')
	tstr = c(tstr,paste('OUTPUTDIR ',od,sep=''))
	tstr = c(tstr,'')
	tstr = c(tstr,'Program control.')
	tstr = c(tstr,'RUNMODE 1')
	tstr = c(tstr,'MISSLEVEL 1')
	tstr = c(tstr,'ITIMPTYPE 0')
	tstr = c(tstr,'HEURTYPE -1')
	tstr = c(tstr,'VERBOSITY 3')
	tstr = c(tstr,'')
	tstr = c(tstr,'SAVESOLUTIONSMATRIX 3')
	return(tstr)
}

#create spec.dat
create.spec.dat = function() {
	tstr = c("id,prop,spf,name")
	tstr = c(tstr,"1,0.3,30,Oceanic atoll")
	tstr = c(tstr,"2,0.3,36,Oceanic Bank")
	tstr = c(tstr,"3,0.3,25,Oceanic island")
	tstr = c(tstr,"4,0.3,33,Continental atoll")
	tstr = c(tstr,"5,0.3,41,Continental bank")
	return(tstr)
}
################################################################################
################################################################################
wd = '/home/jc165798/working/Jessica.Cheok/Testing/'; setwd(wd) #set the workign directory

###make up some data
tdata = matrix(NA,nrow=1000,ncol=8)
colnames(tdata) = c('GUID','lat','lon','PU','MU','FU','area','status')
tdata[,'GUID'] = 1:1000
tdata[,'PU'] = round(runif(1000,1,10))
tdata[,'MU'] = round(runif(1000,1,15))
tdata[,'FU'] = round(runif(1000,1,5))
tdata[,'area'] = 1
tdata[,'status'] = 0 # 0 is available, 2 is locked in, 3 is locked out

###do some work
for (ii in 1:15) {
	id = paste('input',sprintf('%02i',ii),sep=''); dir.create(id) #define and create input directory
	od = paste('output',sprintf('%02i',ii),sep=''); dir.create(od) #define and create input directory
	
	if (ii==1) {
		write.inputs(id) #write out the input files
		twrite2(create.input.dat(od,id,ii),paste('input',sprintf('%02i',ii),'.dat',sep=''))
		twrite2(create.spec.dat(),file.path(id,'/spec.dat'))
		system(command=paste('./MarOpt_v243_Linux32 input',sprintf('%02i',ii),'.dat -s ',sep=''))#,wait=FALSE)
		
	} else {
		ssoln = read.csv(paste('output',sprintf('%02i',ii-1),'/rep',sprintf('%02i',ii-1),'_ssoln.csv',sep='')) #read in solution from previous
		ssoln = ssoln$planning_unit[order(ssoln$number,decreasing=TRUE)[1:2]]
		ssoln.data = tdata[which(tdata[,'PU'] %in% ssoln),]
		aggregate(ssoln.data[,'area'],by=list(FU=ssoln.data[,'FU'],MU=ssoln.data[,'MU'],PU=ssoln.data[,'PU']),sum)
	}

}



###run marxan
dir.create('output1')
writeLines(create.input.dat('output1','input1'),'input.dat1')
system('./MarOpt_v243_Linux64 input.dat1')

######marxan completed... now what...

ssoln = read.

